### ISSUE TITLE
Metadata not found

### ISSUE THREAD

**Issue by xefil** [malnvenshorn/OctoPrint-MetadataPreprocessor#1]
Hello,

As written in the other thread, the metadata is not found because Slic3r put the informations at the end.
Now I've tried to move the informations on the beginning of the gcode, but it not works anyway.
Here how the file starts:
```
; generated by Slic3r Prusa Edition 1.39.1-prusa3d-win64 on 2018-05-24 at 14:14:28

; 
; filament used = 49181.0mm (118.3cm3)
; filament used = 147.9
; total filament cost = 0.0
; estimated printing time = 13h 2m 14s
; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm
```

Hope it helps. Thank you!

Simon

**Comment by malnvenshorn** [comment]
Have you read the [README](https://github.com/malnvenshorn/OctoPrint-MetadataPreprocessor/blob/master/analysis/README.md)? This plugin don't use the data generated by the slicer. You have to run the `analysis.py` script which is a wrapper for OctoPrints `gcodeInterpreter.py`.

**Comment by xefil** [comment]
Ok, sorry, I've misunderstood how it works.
I've installed the zip file (https://github.com/malnvenshorn/OctoPrint-MetadataPreprocessor/archive/master.zip) via plugin manager. Until here ok.
The second step is to install the analysis like descrived in the [README](https://github.com/malnvenshorn/OctoPrint-MetadataPreprocessor/blob/master/analysis/README.md) ?
I'm using Slic3r on Windows without python. It's not clear for me how the post-processing script should work, when it would be executed. Should it upload then the gcode on my RPi and execute the analyzer via cli manually? Wouldn't replace this the original one?
Thanks

**Comment by xefil** [comment]
Hello @malnvenshorn 
Long time ago... I was able to test your script only today.
Installing analysis on a linux box, but I got `ImportError: No module named gcodeInterpreter`
Can you help me?
Thanks!
Simon

**Comment by malnvenshorn** [comment]
Sorry, I totally missed your comment :flushed:

Fixed it with commit 82e4c5d.

**Comment by xefil** [comment]
Uh, one question. I know it's off topic from this thread. btw, you're the autor of FilamentManager as well, right? Do you plan updates there? I've posted question to have, if possible, the ability to archive or hide selected spoons. In example, when they are finished. Deleting them would mean loos the number of used spoons :-) btw: https://github.com/malnvenshorn/OctoPrint-FilamentManager/issues/106#issuecomment-429271354 
Sorry for cross-posting ;)
PS: Patch working!!! TY!

**Comment by malnvenshorn** [comment]
Yes I'm still planning to release updates. At the moment I'm in the process of rewriting certain parts, but haven't had that much time lately :disappointed:

**Comment by xefil** [comment]
Thank you so much, great job meanwhile!!
